proxy_cache_path /var/cache/nginx/lab levels=1:2 keys_zone=lab_cache:10m max_size=256m inactive=15m use_temp_path=off;

limit_req_zone $binary_remote_addr zone=api_rate:10m rate=5r/s;
limit_conn_zone $binary_remote_addr zone=client_conn:10m;

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
